### ISSUE TITLE
sh Error On Running

### ISSUE THREAD

**Issue by conatus** [DTrejo/rotten#11]
```
› rotten --prod develop 
Checking that branches are in production branch develop
.
 Error: Command failed: /bin/sh: origin/master: No such file or directory

    at onBranch (/usr/local/share/npm/lib/node_modules/rotten/rotten.js:65:36)
    at ChildProcess.exithandler (child_process.js:544:7)
    at ChildProcess.EventEmitter.emit (events.js:99:17)
    at maybeClose (child_process.js:638:16)
    at Socket.ChildProcess.spawn.stdin (child_process.js:815:11)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Socket._destroy.destroyed (net.js:357:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
............
  origin/refactor/ui-fixes all in prod, please delete remote branch
  origin/refactor/tests-fix all in prod, please delete remote branch
  origin/refactor/rename-to-pp all in prod, please delete remote branch
  origin/refactor/remove-profiler all in prod, please delete remote branch
```

etc etc all okay.

Running Rotten against http://github.com/unikent/programmes-plant

Might be a local problem. Seems to otherwise work.

Cheers!

**Comment by DTrejo** [comment]
Hey, I was able to reproduce, sadly.

Looking into it.

So: it is trying to run 

`git log origin/HEAD -> origin/master --not --remotes="*/develop" --format="%H | %ae | %ce | %ar | %cr | %ct"`

but of course it does not work since it's trying to compare HEAD and master.

The fix is to ignore HEAD, I think?

OH, it seems like your repo has the branch origin/HEAD, which is not so normal?

Your branch list:

```
  origin/HEAD -> origin/master
  origin/bug/correct-caching-on-saving
  origin/bug/headers-incorrect
  ...
```

Not sure what to do about this: maybe just ignore branchnames which contain "->" or spaces?

Thoughts?
D
